### ISSUE TITLE
Cleaning community data for QUE 2020

### ISSUE THREAD

**Issue by TanyaS08** [TanyaS08/PFTC5_Gr3#5]
These are the species that have no match with the data on osf - it might be that the species names listed here are correct and it isn't an error e.g. _Bartsia inaequalis_.

_Calamagrostis sp8            
Geranium filipes  - Geranium sessiliflorum           
Festuca cf. andina           
Calamagrostis sp7            
Oreobolus sp1              
Festuca 3 sharp              
Bartsia inaequalis           
Agrostis sp1                 
Calamagrostis cf. macrophylla_
~_Jamesonia alstonii_  ~
+ ~This one is odd since it is in the other dataset but I can't seem to get the strings to match... ~ added family and functional group data see commit #7fc2f6b

_Calamagrostis tricophylla_    

@audhalbritter should I send this and the script to Paul and Lucely to have a look at? If they are working on a public repo I can always make a PR - which is probably the best (easiest) approach. There are a few 'punctuation errors' I picked up in the osf dataset as well

**Comment by audhalbritter** [comment]
Yes, please ask Lucely and Paul to confirm the species names and correct. The sp3 and Festuca sharp etc are probably names that we do not know yet. But Lucely will know what they are.

**Comment by TanyaS08** [comment]
All flagged species corrected and accounted for - see commit 5a9ab9b
